# -*- coding: utf-8 -*-
"""TCC - Tratamento Dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12IwPZ6ZSkoIV_emnFVyG_q553UPu_CSs
"""

import pandas as pd

def ler_csvs(teste: str, metodo: str):
  tabela = pd.read_csv(f"{metodo}/metricas_finais_{teste}_{metodo}.csv", usecols=['Accuracy', 'Precision_macro', 'Recall_macro', 'F1_macro', 'MCC', 'ROC_AUC_macro'])
  carbon = pd.read_csv(f"{metodo}/emissions_{teste}_{metodo}.csv", usecols=['duration', 'emissions'])

  dataset = pd.concat([tabela, carbon], axis=1)

  return dataset

def calcular_medias(datasets):
    # Junta os datasets
    dados = pd.concat(datasets, ignore_index=True)

    # Calcula a média de cada coluna
    medias = dados.mean(numeric_only=True)

    return medias

testes = [
    "teste1",
    "teste2",
    "teste3",
    "teste4",
    "teste5"
]

metodos = [
    "FFT_SVM",
    "FFT_RF",
    "DWT_SVM",
    "DWT_RF"
]

datasets= []

for metodo in metodos:
  dataset = []
  for teste in testes:
    dataset.append(ler_csvs(teste, metodo))
  
  medias = calcular_medias(dataset)
  datasets.append(medias)

# print(datasets[0])
tabela_comparativa = pd.DataFrame(datasets).rename(columns={
    "Precision_macro": "Precision",
    "Recall_macro": "Recall",
    "F1_macro": "F1",
    "ROC_AUC_macro": "ROC_AUC",
    "duration": "Duração",
    "emissions": "Emissão CO2 (kg)"
})[["Accuracy", "Precision", "Recall", "F1", "MCC", "ROC_AUC", "Duração", "Emissão CO2 (kg)"]]

tabela_comparativa.insert(0, "Método", [metodo.replace("_", " + ") for metodo in metodos])

tabela_comparativa.to_csv("Métricas.csv", index=False)

# for a in tabelas_FFT_SVM:
#   print(a)

# tabela_fft_svm = pd.read_csv("metricas_finais.csv", sep=",")
# carbon_fft_svm = pd.read_csv("emissions_fft_svm.csv", sep=",")

# tabela_fft_rf = pd.read_csv("metricas_finais_FFT_RandomForest.csv", sep=",")
# carbon_fft_rf = pd.read_csv("emissions_fft_rf.csv", sep=",")

# tabela_wvt_svm = pd.read_csv("metricas_finais_Wavelet_SVM.csv", sep=",")
# carbon_wvt_svm = pd.read_csv("emissions_wvt_svm.csv", sep=",")

# tabela_wvt_rf = pd.read_csv("metricas_finais_Wavelet_RandomForest.csv", sep=",")
# carbon_wvt_rf = pd.read_csv("emissions_wvt_rf.csv", sep=",")

# tabela_comparativa = pd.DataFrame()

# tabela_comparativa["Método"] = [
#     "FFT + SVM",
#     "FFT + RF",
#     "Wavelet + SVM",
#     "Wavelet + RF"
# ]

# tabela_comparativa["Acurácia"] = [
#     tabela_fft_svm["Accuracy"].iloc[0],
#     tabela_fft_rf["Accuracy"].iloc[0],
#     tabela_wvt_svm["Accuracy"].iloc[0],
#     tabela_wvt_rf["Accuracy"].iloc[0]

# ]

# tabela_comparativa["Precisão"] = [
#     tabela_fft_svm["Precision_macro"].iloc[0],
#     tabela_fft_rf["Precision_macro"].iloc[0],
#     tabela_wvt_svm["Precision_macro"].iloc[0],
#     tabela_wvt_rf["Precision_macro"].iloc[0]
# ]

# tabela_comparativa["Recall"] = [
#     tabela_fft_svm["Recall_macro"].iloc[0],
#     tabela_fft_rf["Recall_macro"].iloc[0],
#     tabela_wvt_svm["Recall_macro"].iloc[0],
#     tabela_wvt_rf["Recall_macro"].iloc[0]
# ]

# tabela_comparativa["F1 - Macro"] = [
#     tabela_fft_svm["F1_macro"].iloc[0],
#     tabela_fft_rf["F1_macro"].iloc[0],
#     tabela_wvt_svm["F1_macro"].iloc[0],
#     tabela_wvt_rf["F1_macro"].iloc[0]
# ]

# tabela_comparativa["MCC"] = [
#     tabela_fft_svm["MCC"].iloc[0],
#     tabela_fft_rf["MCC"].iloc[0],
#     tabela_wvt_svm["MCC"].iloc[0],
#     tabela_wvt_rf["MCC"].iloc[0]
# ]

# tabela_comparativa["ROC AUC"] = [
#     tabela_fft_svm["ROC_AUC_macro"].iloc[0],
#     tabela_fft_rf["ROC_AUC_macro"].iloc[0],
#     tabela_wvt_svm["ROC_AUC_macro"].iloc[0],
#     tabela_wvt_rf["ROC_AUC_macro"].iloc[0]
# ]

# tabela_comparativa["Duração"] = [
#     carbon_fft_svm["duration"].iloc[0],
#     carbon_fft_rf["duration"].iloc[0],
#     carbon_wvt_svm["duration"].iloc[0],
#     carbon_wvt_rf["duration"].iloc[0]
# ]

# tabela_comparativa["Emissão CO2 (kg)"] = [
#     carbon_fft_svm["emissions"].iloc[0],
#     carbon_fft_rf["emissions"].iloc[0],
#     carbon_wvt_svm["emissions"].iloc[0],
#     carbon_wvt_rf["emissions"].iloc[0]
# ]


# tabela_comparativa.to_csv("Métricas.csv", index=False)

# display(tabela_comparativa)